package com.cricketleague;

public enum SortedField {
    AVG,StrikeRate,RUN, TOTALSIXANDFOUR, AVERAGEWITHSTRIKERATE, MAXRUNWITHBESTAVG, BESTSTRIKERATEWITHSIXANDFOUR, Economy, BESTSTRIKERATEWITHFOURANDFIVEWICKETS;
}
