package com.cricketleague;

public enum SortedField {
    AVG, Strike_Rate,RUN, TOTAL_SIX_AND_FOUR, AVERAGE_WITH_STRIKE_RATE, MAX_RUN_WITH_BEST_AVG, BEST_STRIKE_RATE_WITH_SIX_AND_FOUR,
    Economy, BEST_STRIKE_RATE_WITH_FOUR_AND_FIVE_WICKETS, BEST_BOWLING_AVG_WITH_STRIKE_RATE, MAXIMUM_WICKET_WITH_BEST_BOWLING_AVG,
    BEST_BATTING_BOWLING_AVG;
}
